### ISSUE TITLE
Padrão de Projeto Observer

### ISSUE THREAD

**Issue by ana-molinos** [caio-o/ggg#13]
###  Observer
> Estudo e implementação do padrão de projeto _Observer_. O _Observer_ é um padrão de projeto comportamental que permite que você defina um mecanismo de assinatura para notificar múltiplos objetos sobre quaisquer eventos que aconteçam com o objeto que eles estão observando. (Definição retirada do site)
Ex.: Um observador que cuida do jogador 1 e notifica quando as teclas cima, baixo, esquerda ou direita são pressionadas ou soltas.

- [x] Assistir vídeos sobre o pp
  - [x] Burda
  - [x] Geovane
- [ ] Assistir vídeos sobre gerenciador de estados
   - [ ] Burda
   - [ ] Geovane
- [x] Estudar a respeito (links do peteco)
   - [x] Slides apresentação: https://drive.google.com/file/d/1Usp6f_C62zjFf5vyUmDZWFWoWKfAMZre/view?usp=drive_link
   - [x] Texto informativo: https://docs.google.com/document/d/1bPm4oCkVGdTrKYgrAJdVZInh7qVzSwWEdAPLD8Wpd5M/edit?usp=sharing
   - [x] Site a respeito de pp: https://refactoring.guru/pt-br/design-patterns
- [ ] Modelar
- [ ] Implementar
- [ ] Testar
- [ ] Subir

**Comment by ana-molinos** [comment]
### Anotações

- Classe Publicadora ou Sujeito (Gerenciador de eventos): a classe que repassa a informação para os objetos das classes interessadas quando algo acontece. Ela possui uma lista de interessados (os observadores) e chama os métodos especifícos de notificação deles.
- Observadores (interface): são os mediadores entre publicadora e assinante. Devem receber via parâmetro informações relevantes que serão repassadas ao objeto assinante (qual foi a tecla pressionada, por ex.). Chamam o método de notificação dos objetos que eles observam.
- Classe Assinante ou Observado (i.e. Jogadores, Menu): é a classe que tem interesse em receber a notificação. Ela precisa possuir métodos específicos para ser notificada que designa qual ação deve ser tomada pelo objeto frente ao acontecimento notificado pelo observador.

**Fluxo:** gerenciador de eventos "captura" alguma ação -> essa ação é notificada para os seus observadores -> os observadores repassam para os objetos pertinentes que realizam outra ação resposta

**Estrutura:**
- Observador (abstrata)
   - ObservadorJogador
   - ObservadorMenu (checar se é necessario ter um observador pra cada tipo de menu)

**Obs.:** o burda ainda implementa uma quarta classe que é um gerenciador de Input. Ou seja, se o gerenciador de eventos detecta um evento relacionado a entradas do teclado (e mouse, se for o caso), ele aciona o gerenciador de input. O gerenciador de input serve para desacoplamento da biblioteca gráfica. Ele transforma os parâmetros recebidos (sf::Keyboard::Key) em strings, para que o restante do código possa utilizar essa informação sem depender do SFML. O **fluxo**, por sua vez, se torna o seguinte: gerenciador de eventos -> gerenciador de input -> observadores -> menu/jogadores

**Comment by caio-o** [comment]
Legal. Parece útil esse padrão. Com isso o Jogador, o Menu, etc. ficam independentes do Gerenciador de Eventos, né? Vou dar uma olhada.

**Comment by ana-molinos** [comment]
**Diferenças entre o código do burda e do geovane:** o burda declara um atributo booleano nas classes Jogador e Menu para definir se o objeto está ativo ou não, logo os métodos de resposta às ações notificadas pelos observadores só vão rodar se o booleano for true. Já, o geovane declara esse booleano nos observadores. Se o estado atual é o menu de pausa, apenas o observador do menu de pausa vai estar ativo e os demais objetos não vão ser notificados sobre os eventos. Esse atributo se relaciona também com o gerenciador de estados. Essa última opção parece mais coerente.

**Comment by ana-molinos** [comment]
### **Adendo:**
Acredito que será necessário implementar um gerenciador de estados antes da implementação do Observer e dos Menus :').
