### ISSUE TITLE
Arrumar diagrama de classes v1

### ISSUE THREAD

**Issue by ana-molinos** [caio-o/ggg#19]
### Correção de diagrama de classes
> Correções para reunião com Simão quarta-feira, 21/08 às 15h30.

- [x] Acertar posição
- [x] Juntar minha parte
- [x] Conferir se as classes bases tem os métodos base solicitados pelo Simão

**Comment by caio-o** [comment]
Está pronto. Amanhã de manhã vou à gráfica mandar imprimir.
